//! Codex agent driver
//!
//! Merges all agent files into a single `.codex/AGENTS.md` file.

use std::path::{Path, PathBuf};

use anyhow::Result;

use super::AgentDriver;

/// Path to the merged agents file for Codex
const CODEX_AGENTS_FILE: &str = ".codex/AGENTS.md";

/// Codex agent driver
pub struct CodexDriver;

impl AgentDriver for CodexDriver {
    fn name(&self) -> &'static str {
        "codex"
    }

    fn agents_dir(&self, workspace_dir: &Path) -> PathBuf {
        workspace_dir.join(".codex")
    }

    fn agent_patterns(&self) -> &'static [&'static str] {
        &["AGENTS.md", ".codex/AGENTS.md"]
    }

    fn install_agents(&self, workspace_dir: &Path, agent_paths: &[PathBuf]) -> Result<usize> {
        if agent_paths.is_empty() {
            return Ok(0);
        }

        let codex_dir = self.agents_dir(workspace_dir);
        std::fs::create_dir_all(&codex_dir)?;

        // Merge all agent files into a single file
        let merged_path = workspace_dir.join(CODEX_AGENTS_FILE);
        let mut merged_content = String::new();

        merged_content.push_str("# Barrel Agents\n\n");
        merged_content.push_str("<!-- Auto-generated by barrel. Do not edit. -->\n\n");

        let mut count = 0;
        for source_path in agent_paths {
            let name = derive_agent_name(source_path);
            let content = std::fs::read_to_string(source_path)?;

            // Strip YAML frontmatter if present
            let content = strip_frontmatter(&content);

            merged_content.push_str(&format!("## {}\n\n", name));
            merged_content.push_str(content.trim());
            merged_content.push_str("\n\n---\n\n");
            count += 1;
        }

        std::fs::write(&merged_path, merged_content)?;

        Ok(count)
    }

    fn cleanup(&self, workspace_dir: &Path) -> bool {
        let codex_file = workspace_dir.join(CODEX_AGENTS_FILE);
        // Only remove if it's a barrel-generated file
        if let Ok(content) = std::fs::read_to_string(&codex_file)
            && content.contains("<!-- Auto-generated by barrel.")
        {
            return std::fs::remove_file(&codex_file).is_ok();
        }
        false
    }
}

/// Derive agent name from file path
fn derive_agent_name(path: &Path) -> String {
    if path.file_name().map(|n| n == "AGENT.md").unwrap_or(false) {
        path.parent()
            .and_then(|p| p.file_name())
            .map(|n| n.to_string_lossy().to_string())
            .unwrap_or_else(|| "agent".to_string())
    } else {
        path.file_stem()
            .map(|n| n.to_string_lossy().to_string())
            .unwrap_or_else(|| "agent".to_string())
    }
}

/// Strip YAML frontmatter from markdown content
fn strip_frontmatter(content: &str) -> &str {
    content
        .strip_prefix("---")
        .and_then(|after| after.find("\n---").map(|idx| after[idx + 4..].trim_start()))
        .unwrap_or(content)
}
